# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testhtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('date', models.TextField()),
            ],
        ),
    ]
