# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhtml',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
