# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-13 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEproject', '0003_auto_20161113_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
