# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
