# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default='blank@qq.com', max_length=254),
        ),
    ]
